name: deploy
run-name: Build application and test
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Install Dependencies
        run: go get ./GoDB
      - name: Go build
        run: go build -v ./...
      - name: Test
        run: go test -v ./GoDB/Tests
      - name: Test and upload artifact
        run: go test ./GoDB/Tests -json > TestResults.json
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json